### ISSUE TITLE
Cant change messages

### ISSUE THREAD

**Issue by shaqupl** [iBuseWinner/Reputation#2]
Hi, Im from Poland. I was looking for plugin just like your's and It's all I've been looking for. Really great plugin.
The problem is that I was trying to use it on 1.16.4 paper and its working, but I can't change messages to Polish. I've also tried your EN version and still nothing. Every command works besides /rep reload. After executing that command plugin crashes and it can't be use no more until next server restart.
Please can you add support for 1.16.4? I would be very greatfull for that.

**Comment by iBuseWinner** [comment]
Hello. Can you send log with exception?

**Comment by shaqupl** [comment]
[Reputation.zip](https://github.com/iBuseWinner/Reputation/files/6054256/Reputation.zip)
So here is logs and config. Glad you responded, still need that plugin badly.

**Comment by iBuseWinner** [comment]
Line 78: you forgot ' at the end.

**Comment by iBuseWinner** [comment]
I'm sorry I didn't answer

**Comment by shaqupl** [comment]
Hi, It helped but still got problem after executing **/rep get** i get errors. I've seen that you updated plugin to 2.2 but only in russian spigot could you also post update on spigot.org ? Here is error log:

`[04:46:10] [Server thread/INFO]: Kuszaa issued server command: /rep get
[04:46:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rep' in plugin Reputation v2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-563]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-563]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-563]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-563]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at ru.buseso.spigot.free.reputation.RepCmd.onCommand(RepCmd.java:29) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-563]
	... 19 more`

**Comment by iBuseWinner** [comment]
https://www.spigotmc.org/resources/reputation-give-players-the-right-to-choose-the-best-one.77146/update?update=393911

Don't forgot to get new config: https://github.com/iBuseWinner/Reputation/blob/master/src/main/resources/config.yml

**Comment by shaqupl** [comment]
I downloaded new version and everything works perfect. You could consider this function:
When you add/remove reputation to player by **/rep + [player]**,  **/rep undo** should also remove cooldown.

**Comment by iBuseWinner** [comment]
Hmm...
Okay, I'll add this feature soon....

Idk when will be next update

**Comment by shaqupl** [comment]
I found out that **/rep undo +/-** doesn't work. I've added rep + to the player and then tried to **/rep undo+** and output is **
![image](https://user-images.githubusercontent.com/68109218/111972375-b13f3280-8afd-11eb-9405-38a8f81cabec.png)

**Comment by iBuseWinner** [comment]
Erm... Forgot to add this when recoded command

**Comment by shaqupl** [comment]
I also have proposition to make reputation even better.
You can add function that prevent **player1** to duplicate repuation for **player2**.
For example cooldown for **rep+** is **3600s** so **player1** can add +1 rep to **player2** and as cooldown expire **player1** can add +1 rep to **player3** but still can't add rep to **player2**.
I hope that you will understand my english is very poor.

**Comment by iBuseWinner** [comment]
**player1** will not be able to send the reputation of **player2** anyway

**Comment by shaqupl** [comment]
Awesome I didin't knew that. Thanks for all. Great plugin.

**Comment by iBuseWinner** [comment]
Thank you for review ❤️

**Comment by iBuseWinner** [comment]
**/rep undo** will be added in next update
