### ISSUE TITLE
Плагин не запускается на версии 1.12.2

### ISSUE THREAD

**Issue by RemForever0** [iBuseWinner/Reputation#23]
Указано, что поддерживается версия майнкрафта с 1.8-1.20, но по итогу Java версия плагина 16 (60), на моем сервере же стоит Java 8

[13:42:15] [Server thread/ERROR]: Could not load 'plugins/Reputation-3.0.12-БЕТА.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: ru/fennec/free/reputation/ReputationPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.UnsupportedClassVersionError: ru/fennec/free/reputation/ReputationPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
	... 6 more

**Comment by iBuseWinner** [comment]
Ок, устрою плагину деградацию до 8 джавы. Ждите.

**Comment by iBuseWinner** [comment]
Вот, держите, распишитесь, 3.0.13-БЕТА. Скомпилирована под java 8.
https://spigotmc.ru/resources/reputation-dajte-igrokam-pravo-vybora-luchshego-iz-nix-mysql-sqlite-bukkit-spigot-paper.124/version/4741/download

Но, ради святого нотча, пожалуйста, перейдите уже на нормальные версии, 1.12.2 была выпущена в 2017 году, 7 лет уже прошло, версия не актуальна сама по себе.
