### ISSUE TITLE
Не работает PlaceholderAPI

### ISSUE THREAD

**Issue by VanyaGaming** [iBuseWinner/Reputation#4]
Здравствуй. У меня не работает PlaceholderAPI ни на голограммах, ни в меню. Ядро: Purpur 1.16.5 (fork PaperSpigot). Версии плагинов: HolographicDisplays[2.4.6], HolographicExtension[1.10.9], DeluxMenus[1.13.3] 
[Скрин того что не работает.](https://prnt.sc/10vhyuw)

Ошибка с голограммами:
`[23:57:16] [Server thread/ERROR]: [HolographicExtension] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.NullPointerException: null
	at ru.buseso.spigot.free.reputation.Reputation.getOnlineRepPlayerByNick(Reputation.java:217) ~[?:?]
	at ru.buseso.spigot.free.reputation.Reputation.getRepPlayerByNick(Reputation.java:244) ~[?:?]
	at ru.buseso.spigot.free.reputation.Utils.RepExpansion.onPlaceholderRequest(RepExpansion.java:33) ~[?:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at net.kitesoftware.holograms.listener.PacketPlaceholderListener.replacePlaceholders(PacketPlaceholderListener.java:98) ~[?:?]
	at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:65) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:488) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:337) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1860) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1833) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:2511) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:458) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.EntityTrackerEntry.lambda$broadcastIncludingSelf$4(EntityTrackerEntry.java:455) ~[patched_1.16.5.jar:git-Purpur-1016]
	at gg.airplane.structs.TrackQueue.runMainThreadTasks(TrackQueue.java:54) ~[patched_1.16.5.jar:git-Purpur-1016]
	at gg.airplane.structs.TrackQueue.start(TrackQueue.java:44) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2168) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap.g(PlayerChunkMap.java:2198) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1069) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:925) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:937) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1442) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:391) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1016]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1016]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[23:57:16] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutEntityMetadata@36b1a163[
    a=250
    b=[net.minecraft.server.v1_16_R3.DataWatcher$Item@59546ff3, net.minecraft.server.v1_16_R3.DataWatcher$Item@37ba45e6]
  ]`
  
  
  Ошибка от DeluxMenus:
  `[00:03:40 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.13.3-Release generated an exception while executing task 960
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
        at ru.buseso.spigot.free.reputation.Utils.RepExpansion.onPlaceholderRequest(RepExpansion.java:54) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
        at com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(MenuHolder.java:97) ~[?:?]
        at com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:591) ~[?:?]
        at com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$1(Menu.java:262) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1016]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1016]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1016]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by iBuseWinner** [comment]
Ой, возможно из-за того, что берёт только онлайн игроков.
Постараюсь исправить на этих выходных, если будет время.

**Comment by iBuseWinner** [comment]
Какой способ хранения данных используется?
Я так понимаю, что MySQL.

**Comment by VanyaGaming** [comment]
Да, MySQL.


> Какой способ хранения данных используется?
> Я так понимаю, что MySQL.

Да, MySQL.

**Comment by iBuseWinner** [comment]
Тогда проблема скорее всего из-за того, как и в #6

**Comment by iBuseWinner** [comment]
Привет. Починил работу с MySQL.
Просьба проверить.

Ссылка на скачивание версии 2.3 (бета, поэтому ещё не на форуме): https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by VanyaGaming** [comment]
Привет. Сейчас решил обратно вернуть репутации, нашел последнюю фикс версию в тикете #6. В консоле ниче не пишет, плагин запускается нормально, но почему на голограмме не отображается топ игроков. 
Версия: Paper 1.12.2, HolographicDisplays[2.4.6].
![image](https://user-images.githubusercontent.com/48959361/120998964-3d720500-c791-11eb-91d4-f22f3cf2bae0.png)

**Comment by VanyaGaming** [comment]
Только что заметил еще вот такую ошибку в консоли:
![image](https://user-images.githubusercontent.com/48959361/121385337-b15b0b80-c951-11eb-95e9-e9d162d573f4.png)

**Comment by iBuseWinner** [comment]
Какие настройки в конфиге (кроме пароля и логина от бд)?

**Comment by VanyaGaming** [comment]
> Какие настройки в конфиге (кроме пароля и логина от бд)?

`settings:
  #Here you need to choose where the data about the players will be stored.
  #Здесь Вам необходимо указать, где будут храниться данные об игроках.
  data:
    #Avalible types: yaml, MySQL. Default: yaml
    #Доступные типы: yaml, MySQL. По стандарту: yaml
    type: MySQL

    #Don't touch if type is yaml!!
    #Не трогать, если тип yaml!!
    sql:
      host: 'localhost'
      port: 3306
      database: 'all'
      user: ''
      password: ''
      table: 'reputation'

  #How many people will be in the top. (/rep top). Default: 5
  #Сколько человек будет в топе. По стандарту: 5
  top-limit: 5
  #Can a player’s reputation go negative? Default: true
  #Может ли репутация игрока уйти в минус? По стандарту: true
  #Will be soon... | Будет скоро...
  can-negative: true
  #Check if there are plugin updates or not. Default: true
  #Проверять, есть ли обновления плагина или нет. По стандарту: true
  check-updates: true
  #Show a full description of the error when it occurs. Default: true
  #Показывать полное описание ошибки, когда она возникает. По стандарту: true
  debug-mode: false
  #Auto-save player's data
  #Авто-сохранение информации об игроках
  #
  #Avalible modes: | Доступные режимы:
  #-1 - disabled | выключено
  #0 - when player quit the server | когда игрок выходит с сервера
  #1 and more - every X minutes + when player quit the server | 1 и больше - каждые Х минут + когда игрок выходит с сервера
  #Default: 0 (RECOMMENDED)
  auto-save: 0
  #Cooldowns for command /reputation (and aliases)
  #Задержки для команды /reputation (и алиасов)
  cooldowns:
    #Need to enable cooldowns?
    #Надо ли включить задержки?
    enabled: true
    #Only for /rep + and /rep - or other sub-commands too?
    #Только для /rep + и /rep - или для остальных под-команд тоже?
    only-add-and-remove: true
    #Cooldown in seconds
    #Задержка в секундах
    time-in-sec:
      #permission: time
      default: 60
      vip: 30
      owner: 5

  #Allows players add/remove unlimited reputations or only one time?
  #We don't recommend to enable this feature to prevent dupes
  #Разрешить игрокам добавлять/убирать бесконечно раз репутацию или только один раз?
  #Мы не рекомендуем включать эту фичу, чтобы пресечь дюпы
  can-unlimited-reps: false`

**Comment by iBuseWinner** [comment]
Завтра посмотрю, что не так, и попробую исправить.

**Comment by VanyaGaming** [comment]
> Завтра посмотрю, что не так, и попробую исправить.

Хорошо

**Comment by iBuseWinner** [comment]
Правильный placeholder: %rep\_top\_1\_nick%

Я у себя проверил, всё работает, ошибок нет...
На всякий случай кидаю версию 2.3.1, возможно, тут у тебя тоже не будет ошибок.
https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by VanyaGaming** [comment]
![image](https://user-images.githubusercontent.com/48959361/121560843-95726b00-ca20-11eb-91a5-0a785b552c3d.png)

Ошибок нету, но вот они всё равно не работают... При включении плагина пишет что rep успешно зарегистрирован. 
![image](https://user-images.githubusercontent.com/48959361/121561708-6d373c00-ca21-11eb-9e6f-7316fd631278.png)

Но потом когда в конце запускается сам PAPI, то я не вижу чтобы было rep среди них.
![image](https://user-images.githubusercontent.com/48959361/121561922-9fe13480-ca21-11eb-924a-02274a7b0ef3.png)

**Comment by VanyaGaming** [comment]
И на самом сервере тоже нету Rep
![image](https://user-images.githubusercontent.com/48959361/121563029-b50a9300-ca22-11eb-858f-4a6be937501b.png)

**Comment by iBuseWinner** [comment]
Довольно странно. Даже /papi parse me %rep_rep% не работает?
Какой версии PlaceholderAPI? Может они там что-то изменили...

**Comment by VanyaGaming** [comment]
> Довольно странно. Даже /papi parse me %rep_rep% не работает?
> Какой версии PlaceholderAPI? Может они там что-то изменили...

![image](https://user-images.githubusercontent.com/48959361/121569142-26e5db00-ca29-11eb-97c1-c9caf8c93a13.png)

![image](https://user-images.githubusercontent.com/48959361/121569176-2f3e1600-ca29-11eb-8a40-3fba04582908.png)

**Comment by iBuseWinner** [comment]
Хмм... У меня с такой же версией PAPI работает всё...

**Comment by VanyaGaming** [comment]
> Хмм... У меня с такой же версией PAPI работает всё...

Чисто ради интереса перекачал PAPI. И не работает. 
Почему же мне постоянно так везет на баги. У всех все супер работает, а у меня нет :(

**Comment by iBuseWinner** [comment]
Чисто ради интереса, есть Plugman? Если через него перезагрузить Reputation, то будет какой-нибудь результат?

**Comment by VanyaGaming** [comment]
> Чисто ради интереса, есть Plugman? Если через него перезагрузить Reputation, то будет какой-нибудь результат?

Не использую данный плагин.

**Comment by iBuseWinner** [comment]
Попробуй включить debug-mode в конфиге. Какой-то результат?

**Comment by VanyaGaming** [comment]
> Попробуй включить debug-mode в конфиге. Какой-то результат?

Включён. Запуск как и без него происходит, точнее ничего нового не пишется.
![image](https://user-images.githubusercontent.com/48959361/121577660-6c5ad600-ca32-11eb-8910-89204e96b5ed.png)

**Comment by iBuseWinner** [comment]
Что выдаёт /papi dump?
Есть ещё что-то в логах от PlaceholderAPI и Reputation?

**Comment by iBuseWinner** [comment]
> https://paste.helpch.at/nibopigiqo

А rep записан как рабочий...
До сих пор такая проблема?

К слову о /papi list, он не показывает плагины, в которые вшит placeholder, только те, которые скачиваются через /papi ecloud download

**Comment by VanyaGaming** [comment]
> > https://paste.helpch.at/nibopigiqo
> 
> А rep записан как рабочий...
> До сих пор такая проблема?

Да. :(

> 
> К слову о /papi list, он не показывает плагины, в которые вшит placeholder, только те, которые скачиваются через /papi ecloud download

У меня в нем отображаются и некоторые которые не через команду.

Может что-то еще нужно для работы? Например какая джава? У меня 8 используется.

**Comment by iBuseWinner** [comment]
Пока что ничего не нужно. Мы попробуем с агентом поддержки PlaceholderAPI (Дискорд HelpChat) разобраться, почему такая проблема.

**Comment by VanyaGaming** [comment]
Тут в консоли пишется ошибка после выхода: [https://pastebin.com/j0rUZm1z](https://pastebin.com/j0rUZm1z)

**Comment by VanyaGaming** [comment]
Ничего не известно еще?
