### ISSUE TITLE
Ошибка в консоли (в чате) при использовании команд плагина, когда плагин подключен к базе данных

### ISSUE THREAD

**Issue by NikitaMain** [iBuseWinner/Reputation#6]
Плагин успешно подключается к базе данных:

[15:02:24] [Server thread/INFO]: [Reputation] Enabling Reputation v2.2
[15:02:24] [Server thread/INFO]: Репутация >> Config enabled!
[15:02:24] [Server thread/INFO]: Репутация >> Continue to run the plugin...
[15:02:24] [Server thread/INFO]: Репутация >> Connecting to MySQL...
[15:02:24] [Server thread/WARN]: Mon Apr 05 15:02:24 VLAT 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[15:02:24] [Server thread/INFO]: Репутация >> Репутация >> Успешно подключено к MySQL!
[15:02:24] [Server thread/INFO]: Репутация >> Creating table if not exists...
[15:02:25] [Server thread/INFO]: Репутация >> Auto-save player information: quit mode.
[15:02:25] [Server thread/INFO]: Репутация >> Trying to find PlaceholderAPI...
[15:02:25] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: rep
[15:02:25] [Server thread/INFO]: Репутация >> PlaceholderAPI found!
[15:02:25] [Server thread/INFO]: Репутация >> Plugin successfully enabled!

Ошибка в консоли:

[15:03:21] [Server thread/INFO]: Player2 issued server command: /rep get
[15:03:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rep' in plugin Reputation v2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.12.2.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at ru.buseso.spigot.free.reputation.RepCmd.onCommand(RepCmd.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2.jar:git-Paper-1618]
	... 15 more

**Comment by iBuseWinner** [comment]
Привет. Постараюсь исправить на этих выходных, если будет свободное время.

**Comment by iBuseWinner** [comment]
В БД сам игрок добавляется?

**Comment by NikitaMain** [comment]
Не добавляется.

**Comment by NikitaMain** [comment]
Плагин подключается к базе данных, создает таблицу (которая указана в конфиге). При заходе игрока начинают сыпаться ошибки от тех плагинов, где указаны плэйсхолдеры плагина. Игрок в бд не добавляется. После выполнения любой команды плагина тоже выдает ошибку в консоли, которая указана выше. В чате выдает ошибку: An internal error occurred while attempting to perform this command. Если же не использовать бд, то плагин работает нормально, без ошибок.

**Comment by iBuseWinner** [comment]
Тогда я понял, в чём ошибка. Постараюсь исправить к вечеру. Если сегодня сюда не отпишу, то будет завтра...
(Надеюсь)

**Comment by iBuseWinner** [comment]
Привет. Починил работу с MySQL.
Просьба проверить.

Ссылка на скачивание версии 2.3 (бета, поэтому ещё не на форуме): https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by NikitaMain** [comment]
Теперь работает. Игроки стали добавляться в бд. Но, при попытке отдать очко репутации любому игроку (которому я не выдавал очко репутации), в чат пишет: Вы уже отдали очко репутации другому игроку! (В бд у этого игрока 0 очков репутации)

**Comment by iBuseWinner** [comment]
Посмотрю, что там не так, на выходных.

**Comment by iBuseWinner** [comment]
@NikitaMain теперь должно работать.
https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by NikitaMain** [comment]
Также не работает. Еще, 1. Если посмотреть сколько очков репутации у игрока с помощью команды /rep <ник> (указываю ник игрока, который заходил на сервер и есть в бд), то пишет: Игрок не найден!, 2. Если посмотреть количество очков репутации у себя, используя команду /rep get, то в чат ничего не пишет.

**Comment by iBuseWinner** [comment]
Хммм, а это вообще странно.
Перепроверю всё на выходных и посмотрю...
Если у меня не получится, то я тебе создам дебаг версию плагина, чтобы игрокам и в консоль писались данные, с которыми плагин работает в данный момент. Хочу посмотреть, на каком моменте плагин обкакивается и почему не выводит тебе информацию.

**Comment by iBuseWinner** [comment]
> 1. Если посмотреть сколько очков репутации у игрока с помощью команды /rep <ник> (указываю ник игрока, который заходил на сервер и есть в бд), то пишет: Игрок не найден!

Тут понял, в чём проблема. Учитывало только онлайн игроков, поэтому писало, что игрок не найден.
Сейчас отправлю дебаг версию, там будет фикс этого и дебаг для **add**

> 2. Если посмотреть количество очков репутации у себя, используя команду /rep get, то в чат ничего не пишет.

Тоже дебаг сделаю для этого.

**Comment by iBuseWinner** [comment]
При использовании команд get и add в консоль будет писаться разная информация об игроках.
Пришли, пожалуйста, что оно тебе пишет, если ошибки ещё есть.

https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by NikitaMain** [comment]
1. При выполнении команды /rep get:

В консоли:

[01:35:04 INFO]: sender used command `get`
[01:35:04 INFO]: Sender's uuid is aed5efd4-551b-3965-bc28-ae21aa072a66
[01:35:04 INFO]: Checking player *@%
[01:35:04 INFO]: Checking player *@%

В чате также не выводится сообщение.

2. При выполнении команды /rep + Player1:

В консоли:

[01:37:15 INFO]: Sender's data: RepPlayer{nick='Player2', reps=0, repp=[], repm=[]}
[01:37:15 INFO]: Can't unlimited reps (option from config) and player already given repp

В чате по прежнему выводится сообщение: Вы уже отдали очко репутации другому игроку!

**Comment by NikitaMain** [comment]
При включении в конфиге опции can-unlimited-reps эти команды начинают работать нормально.

**Comment by iBuseWinner** [comment]
> эти команды

Обе что ли?

**Comment by iBuseWinner** [comment]
Понял насчёт второго, может так и первое исправится....

**Comment by iBuseWinner** [comment]
https://drive.google.com/file/d/1uV5C1yr6jBNGCW2jY2YnO7QBcXtKw0gL/view?usp=sharing

**Comment by iBuseWinner** [comment]
@NikitaMain приветик. Есть новости?
Просто интересно, работает ли теперь или нет, а то ответа нет уже 2,5 недели

**Comment by NikitaMain** [comment]
Забыл написать. Да, теперь работает.
